services:
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/beszel_agent:/var/lib/beszel-agent
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      - /mnt/adata_su650/.beszel:/extra-filesystems/adata_su650:ro
    environment:
      LISTEN: 45876
      KEY: ${BESZEL_SSH_KEY} # Do not remove quotes around the key
      HUB_URL: ${BESZEL_URL}
      TOKEN: ${BESZEL_TOKEN}
    labels:
      com.centurylinklabs.watchtower.enable: true
  tsdproxy:
    image: almeidapaulopt/tsdproxy:2
    container_name: tsdproxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdproxy-data:/data
      - /srv/tsdproxy/config:/config
    env_file:
      - .env
    # ports:
    #   - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      com.centurylinklabs.watchtower.enable: true
  watchtower:
    container_name: watchtower
    image: docker.io/nickfedor/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_SCHEDULE: 0 0 3 * * *
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATION_TEMPLATE: >
        {{- if .Report -}}
          {{- with .Report -}}
        {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed
              {{- range .Updated}}
        - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
              {{- end -}}
              {{- range .Fresh}}
        - {{.Name}} ({{.ImageName}}): {{.State}}
            {{- end -}}
            {{- range .Skipped}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
            {{- range .Failed}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
          {{- end -}}
        {{- else -}}
          {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
        {{- end -}}
  cloudflare-tunnel:
    image: docker.io/cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    networks:
      - cloudflare
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "10"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ./config/hosts:/etc/hosts
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    labels:
      com.centurylinklabs.watchtower.enable: true
networks:
  default: null
  cloudflare:
    name: cloudflare-tunnel
  tsdproxy: null
volumes:
  tsdproxy-data: null
