name: n8n

services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    ports:
      - 5678:5678
    networks:
      - default
      - tsdproxy
    volumes:
      - storage:/home/node/.n8n
      - ./local-files:/files
    env_file:
      - .env
    restart: unless-stopped
    environment:
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      # WEBHOOK_URL: https://${DOMAIN_NAME}
      DB_TYPE: sqlite
      # DB_TABLE_PREFIX: n8n
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "n8n"
      tsdproxy.container_port: 5678
      com.centurylinklabs.watchtower.enable: true

volumes:
  storage:


networks:
  default:
    name: n8n
  tsdproxy:
    name: tsdproxy
    external: true
