name: n8n

services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    # ports:
    #   - 5678:5678
    networks:
      - default
      - cloudflare
    volumes:
      - storage:/home/node/.n8n
      - ./local-files:/files
    env_file:
      - .env
    environment:
      N8N_PORT: 5678
      # N8N_PROTOCOL: https
      N8N_RUNNERS_ENABLED: true
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      DB_TYPE: sqlite
      # DB_TABLE_PREFIX: n8n_
      WEBHOOK_URL: https://${N8N_HOST}
    labels:
      # tsdproxy.enable: "true"
      # tsdproxy.name: "n8n"
      # tsdproxy.container_port: 5678
      com.centurylinklabs.watchtower.enable: true

volumes:
  storage:


networks:
  default:
    name: n8n
  cloudflare:
    name: cloudflare_tunnel
    external: true
