# Reference: https://github.com/actualbudget/actual/blob/master/packages/sync-server/docker-compose.yml

name: budget

services:
  actual:
    container_name: actual_budget
    image: ghcr.io/actualbudget/actual:latest-alpine
    restart: unless-stopped
    networks:
      - cloudflare
    volumes:
      - ${ACTUAL_DATA_DIR}:/data
    # ports:
    #   - '5006:5006'
    env_file:
      - .env
    healthcheck:
      # Enable health check for the instance
      test: [ 'CMD-SHELL', 'node src/scripts/health-check.js' ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    labels:
      com.centurylinklabs.watchtower.enable: true


networks:
  cloudflare:
    name: cloudflare_tunnel
    external: true
