# Reference: https://github.com/actualbudget/actual/blob/master/packages/sync-server/docker-compose.yml

name: actual

services:
  actual:
    container_name: actual_budget
    image: ghcr.io/actualbudget/actual:latest-alpine
    restart: unless-stopped
    networks:
      - cloudflare
    volumes:
      - ${ACTUAL_DATA_DIR}:/data
    # ports:
    #   - '5006:5006'
    healthcheck:
      test: # Enable health check for the instance
        - CMD-SHELL
        - node src/scripts/health-check.js
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    labels:
      com.centurylinklabs.watchtower.enable: true
      tsdproxy.enable: true
      tsdproxy.name: actual

networks:
  cloudflare:
    name: cloudflare_tunnel
    external: true
  tsdproxy:
    name: tsdproxy
    external: true
