name: speedtest

services:
  speedtest:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:latest
    restart: always
    environment:
      MODE: standalone
    ports:
      - 8080:8080
    networks:
      - tsdproxy
    labels:
      tsdproxy.enable: true
      tsdproxy.name: speedtest

networks:
  tsdproxy:
    external: true
